const QUESTION_DATA = {
  "en": {
    "self": [
      "Who would you be if you stopped rehearsing who you are?",
      "What part of you only exists because someone once misunderstood you?",
      "Which version of yourself are you protecting out of habit, not truth?",
      "If you weren’t the narrator of your life, what would remain?",
      "What do you defend about yourself that no one is attacking?",
      "Who are you when you are not being useful?",
      "What identity are you afraid to outgrow?",
      "What part of your personality feels borrowed?",
      "If no one remembered you as you are now, would you still try to be this person?",
      "What belief about yourself have you never tested?",
      "Who are you beneath your explanation of yourself?",
      "What trait do you exaggerate so you don’t have to reveal something softer?",
      "If you stopped improving yourself, what would surface?",
      "What are you trying to prove — and to whom?",
      "What part of you feels most artificial when you are alone?",
      "If your past could not justify you, who would you become?",
      "What would collapse if you no longer needed to be consistent?",
      "What are you afraid others would discover if they saw you unedited?",
      "What role have you mistaken for your identity?",
      "Who would you be if you were not the sum of your coping strategies?",
      "• Does the English feel sharp enough?",
      "• Does the Spanish feel authentically Chilean-toned (without slang)?",
      "• Too gentle? Too intense?",
      "What part of you survives by being misunderstood?",
      "If you stopped correcting how people see you, what would happen?",
      "What identity would dissolve if you felt truly safe?",
      "Who are you without your achievements?",
      "What version of yourself do you perform most convincingly?",
      "What would change if you stopped narrating your own growth?",
      "What part of you feels unfinished — and wants to remain that way?",
      "If your personality is adaptive, what is it adapting to?",
      "What would it mean to disappoint your former self?",
      "Who would you be if you did not need to be coherent?",
      "What trait of yours feels most rehearsed?",
      "What do you fear losing if you soften?",
      "What part of you is maintained by comparison?",
      "If no one validated you, would you still be this way?",
      "What identity do you return to when you are afraid?",
      "What would collapse if you stopped being impressive?",
      "Who are you in the moment before you answer a question about yourself?",
      "What part of you resists being seen clearly?",
      "What do you exaggerate to avoid feeling small?",
      "If your self-concept loosened, what might enter?",
      "or stay psychologically grounded and human?",
      "What part of you exists only in reaction to someone else?",
      "Who are you when you are not being observed by memory?",
      "What self-image feels safest but smallest?",
      "What identity do you rehearse before entering a room?",
      "What would it mean to be undefined?",
      "What part of you depends on being needed?",
      "Who are you when no one misunderstands you?",
      "What if your personality is just a negotiation?",
      "What part of you feels most fragile when praised?",
      "Who would you be without your resilience story?",
      "What if nothing about you needed defending?",
      "What version of yourself do you revisit when uncertain?",
      "Who are you before language arranges you?",
      "What part of you feels older than your age?",
      "What self-concept collapses when you fail?",
      "What identity have you intellectualised to avoid feeling?",
      "Who would you be without your history?",
      "What part of you wants to remain misunderstood?",
      "What would remain if your personality softened?",
      "What self-description feels most rehearsed?",
      "Who are you when you are not interpreting yourself?",
      "What identity tightens when you feel unseen?",
      "What part of you depends on struggle?",
      "What if the self you protect is already gone?",
      "Who are you without the effort to become?",
      "What remains when self-improvement pauses?",
      "What if your identity is quieter than your fear suggests?",
      "Who are you in the moment before choosing?",
      "What part of you has never been named?",
      "If you stopped holding yourself together, what would fall — and what would stay?",
      "What version of yourself appears when you feel chosen?",
      "What are you afraid would happen if you stopped accommodating?",
      "Who do you blame for a feeling you haven’t owned?",
      "What expectation are you carrying that was never spoken?",
      "What part of you competes where it claims to care?",
      "What do you call love that might actually be fear?",
      "Who are you trying to protect when you stay silent?",
      "What part of you feels most exposed in intimacy?",
      "What dynamic feels familiar — even when it hurts?",
      "If you stopped defining yourself through others, what remains?",
      "Where does fear announce itself first?",
      "What happens in your stomach when you doubt yourself?",
      "What happens physically when you let yourself be ordinary?",
      "What do you criticise in others that unsettles you in yourself?",
      "What desire have you labelled impractical to avoid claiming it?",
      "What emotion do you reframe as logic?",
      "What part of you feels embarrassed by its own need?",
      "What are you unwilling to admit wanting?",
      "What pattern do you excuse because it feels familiar?",
      "What part of you resents what it also desires?",
      "What fear disguises itself as principle?",
      "What do you postpone that quietly matters?",
      "What habit protects you from feeling exposed?",
      "What are you secretly relieved not to confront?",
      "What insecurity hides behind confidence?",
      "What do you blame others for that you repeat?",
      "What part of you thrives on avoidance?",
      "What do you minimise that actually hurts?",
      "What story do you tell to avoid responsibility?",
      "What part of you feels threatened by growth?",
      "What would you have to face if you stopped distracting yourself?",
      "If you stopped defending yourself, what might you notice?",
      "What do you hide behind being “self-aware”?",
      "What contradiction do you live with comfortably?",
      "What flaw do you defend as personality?",
      "What do you avoid because success would expose you?",
      "What do you exaggerate to hide insecurity?",
      "What part of you manipulates subtly?",
      "What are you afraid would collapse if you told the full truth?",
      "What part of you prefers control to connection?",
      "What grievance do you replay to feel justified?",
      "What are you waiting for that keeps you passive?",
      "What part of you enjoys being misunderstood?",
      "What fear hides beneath your strongest opinion?",
      "What pattern would dissolve if you stopped being the victim?",
      "What part of you needs to be exceptional?",
      "What do you secretly feel superior about?",
      "What part of you resists humility?",
      "What do you call “boundaries” that might be avoidance?",
      "What discomfort are you disguising as busyness?",
      "If you stopped narrating your pain, what would remain?",
      "What part of you feels safer sabotaging yourself?",
      "What are you afraid you might become if you succeeded?",
      "What insecurity disguises itself as discernment?",
      "What do you defend that no longer serves you?",
      "What would collapse if you stopped blaming?",
      "What part of you fears being fully accountable?",
      "What part of you performs self-criticism to avoid real change?",
      "What do you justify that quietly costs you?",
      "What desire have you exiled to protect your image?",
      "What discomfort do you project outward?",
      "If you owned every part of yourself, what would integrate?",
      "What promise to yourself did you abandon?",
      "What moment are you still trying to rewrite?",
      "What part of you feels stuck in another year?",
      "What are you carrying forward that belongs behind you?",
      "What do you fear will happen if you stop planning?",
      "What milestone do you believe will make you enough?",
      "What are you avoiding by staying nostalgic?",
      "What does “someday” protect you from?",
      "If this were the only moment available, what would matter?",
      "What do you tell yourself about “later” to stay comfortable now?",
      "What version of yourself are you trying to become?",
      "What does your sense of urgency protect?",
      "What are you holding open that has already closed?",
      "What future do you imagine to justify the present?",
      "What part of you clings to “before”?",
      "What would change if nothing improved?",
      "What are you measuring your life against?",
      "What do you tell yourself about “when things settle”?",
      "What would it mean to stop narrating your evolution?",
      "What part of you exists only in anticipation?",
      "What would change if this was not preparation?",
      "What regret asks for acknowledgment rather than repair?",
      "What part of you fears stillness because it feels final?",
      "What happens if there is no later?",
      "Who would you be without the idea of yourself?",
      "What is constant through every change?",
      "What notices your resistance?",
      "If the question dissolves, what answers?",
      "Who is hearing these words?",
      "What remains when the observer is observed?",
      "Where does the sense of “me” arise?",
      "What is untouched by your effort?",
      "If there is no center, what moves?",
      "If the self is a thought, what thinks it?",
      "What exists before recognition?",
      "Who is looking through your eyes?",
      "What remains when attention turns back on itself?",
      "If there is no thinker, what thinks?",
      "What is constant when the sense of “me” fluctuates?",
      "If the self cannot be found, what continues?"
    ],
    "relationship": [
      "What part of you only exists in the presence of a specific person?",
      "Who do you become when you want to be loved?",
      "What do you tolerate so you don’t have to be alone?",
      "What role do you replay in most of your relationships?",
      "What do you hope someone else will finally confirm about you?",
      "What boundary are you afraid to name?",
      "What are you asking someone else to hold for you?",
      "Who do you become when you are afraid of losing someone?",
      "What resentment have you disguised as patience?",
      "What part of you feels unseen — and how do you contribute to that?",
      "If you stopped trying to be understood, what would shift?",
      "What part of you feels safer misunderstood?",
      "What do you withhold to stay in control?",
      "Who are you trying to convince in this relationship?",
      "What pattern feels inevitable — and isn’t?",
      "What part of you needs the other to stay the same?",
      "What do you call loyalty that might be fear?",
      "What are you asking for indirectly?",
      "What part of you feels threatened by closeness?",
      "What do you assume others owe you?",
      "Who are you when you stop managing perception?",
      "What part of you keeps score?",
      "What expectation would free you if released?",
      "What part of you feels responsible for others’ feelings?",
      "What dynamic do you recreate unconsciously?",
      "What are you protecting when you avoid honesty?",
      "What part of you needs to be right?",
      "What does this relationship allow you to avoid?",
      "Who do you become when conflict appears?",
      "What part of you fears being replaced?",
      "If you stopped anticipating rejection, how would you act?",
      "What part of you needs others to confirm your worth?",
      "What do you project onto others that belongs to you?",
      "What part of you disappears in certain relationships?",
      "Who are you when you are not reacting?",
      "What dynamic survives only because you participate?",
      "What would happen if you stopped over-explaining?",
      "What part of you feels safer in imbalance?",
      "What are you unconsciously training others to expect?",
      "Who are you when you stop compensating?",
      "What part of you fears being truly known?",
      "What would shift if you stopped managing harmony?",
      "What role do you assume when tension rises?",
      "What part of you equates attention with care?",
      "What dynamic dissolves if you withdraw your fear?",
      "What part of you is loyal to dysfunction?",
      "Who are you when you stop chasing resolution?",
      "What expectation have you never voiced?",
      "What part of you keeps relationships predictable?",
      "What would intimacy look like without strategy?",
      "What part of you feels threatened by independence?",
      "What changes if you release the need to be understood?",
      "Who are you without the story of how others treat you?",
      "What part of you seeks control in subtle ways?",
      "What dynamic repeats because it feels deserved?",
      "What would happen if you stopped earning connection?",
      "What part of you feels safest at a distance?"
    ],
    "body": [
      "Where in your body do you hesitate before speaking?",
      "What sensation appears when you tell the truth?",
      "What part of your body tightens when you feel seen?",
      "Where does relief live in you?",
      "What feeling do you translate into thinking?",
      "What does your breath do when you feel unsafe?",
      "Where do you store what you haven’t said?",
      "What sensation returns when you slow down?",
      "What does your body know before your mind agrees?",
      "Where does exhaustion settle?",
      "What does your posture reveal about your mood?",
      "What part of your body asks for attention most often?",
      "What happens in your chest when you feel misunderstood?",
      "Where do you brace without noticing?",
      "What does your jaw hold?",
      "What shifts in your body when you feel accepted?",
      "What sensation do you avoid feeling fully?",
      "What changes in your body when you soften?",
      "If your body could speak clearly, what would it say?",
      "What sensation hums beneath your thoughts right now?",
      "Where does your body resist being still?",
      "What part of you feels electrically alive?",
      "Where does your energy collapse when you say yes too quickly?",
      "What changes in your spine when you feel confident?",
      "Where does your body expand when you feel safe?",
      "What subtle current moves through you when you are honest?",
      "Where does your body shut down when overwhelmed?",
      "What sensation lingers after someone leaves the room?",
      "Where does your body feel most spacious?",
      "Where does your body hold anticipation?",
      "What part of you vibrates before action?",
      "Where does your breath hesitate?",
      "What subtle warmth appears when you forgive?",
      "Where does your body contract when you feel judged?",
      "What sensation rises before emotion is named?",
      "Where does your body feel most grounded?",
      "What changes in your pulse when you tell the truth?",
      "If you followed the energy in your body, where would it lead?",
      "What does your body know that your mind keeps postponing?",
      "Where does your body feel most like home?",
      "What sensation appears when you stop trying?",
      "Where does your body lean when you feel drawn to something?",
      "What changes in your muscles when you feel respected?",
      "Where does your body hold unfinished conversations?",
      "What part of you feels heavy without explanation?",
      "Where does your body feel porous?",
      "What shifts in your shoulders when you release control?",
      "Where does your body remember something your mind has forgotten?",
      "What sensation signals that you are crossing your own boundary?",
      "Where does your body feel most alive?",
      "What subtle trembling appears before courage?",
      "Where does your body soften when you feel safe?",
      "What sensation grows when you are about to speak honestly?",
      "Where does your body feel constricted around certain people?",
      "What part of you feels uncontained?",
      "Where does your body brace before disappointment?",
      "What sensation lingers when you suppress emotion?",
      "If your body led your decisions, what would change?",
      "What sensation exists before you interpret it?",
      "Where does your body feel most transparent?",
      "What changes when you inhabit your feet fully?",
      "Where does your body pulse when you are quiet?",
      "What part of you feels subtly charged right now?",
      "Where does your body feel unfinished?",
      "What sensation appears when you drop your story?",
      "Where does your body feel unguarded?",
      "What happens in your body when you are completely present?",
      "Where does your energy gather before movement?",
      "What part of your body feels like a doorway?",
      "Where does your body feel less separate from the world?",
      "What sensation grows when you allow stillness?",
      "Where does your body resist surrender?",
      "What subtle vibration appears when you stop resisting feeling?",
      "Where does your body feel most honest?",
      "Where does your body feel most connected to breath?",
      "What sensation remains when thought quiets?",
      "Where does your body feel most grounded in gravity?",
      "What part of you feels open without effort?",
      "Where does your body feel like it is listening?",
      "What sensation deepens when you soften your jaw?",
      "Where does your body feel like pure presence?",
      "If you stayed in your body fully for one minute, what might dissolve?",
      "Who is located in this body?",
      "What is here before memory arises?",
      "If nothing is separate, what divides?",
      "What notices the illusion of control?",
      "Who is present without identity?",
      "What is aware without effort?",
      "If there is no center, where do you stand?"
    ],
    "shadow": [
      "What truth do you avoid by staying busy?",
      "What part of you do you pretend isn’t there?",
      "What part of you benefits from staying stuck?",
      "What do you pretend not to understand?",
      "What standard do you hold others to that you quietly break?",
      "What desire do you judge in others because it unsettles you?",
      "What part of you fears being ordinary?",
      "What do you over-explain to avoid scrutiny?",
      "What habit keeps you from risking rejection?",
      "What envy do you rename as criticism?",
      "What truth feels inconvenient right now?",
      "What part of you prefers resentment to responsibility?",
      "What are you protecting when you delay action?",
      "What insecurity hides inside ambition?",
      "What pattern survives because it keeps you comfortable?",
      "What do you perform to hide uncertainty?",
      "What part of you resists accountability?",
      "What do you call “being realistic” that might be fear?",
      "What apology have you never offered?",
      "What part of you wants recognition but rejects visibility?",
      "What discomfort do you outsource to others?",
      "What part of you wants sympathy more than change?",
      "What part of you depends on staying conflicted?",
      "What would you lose if you admitted you were wrong?",
      "What identity survives through subtle dishonesty?",
      "What do you secretly hope never gets exposed?",
      "What do you protect by staying cynical?",
      "What part of you needs someone else to fail?",
      "What discomfort would growth require of you?",
      "What do you criticise because you once wanted it?",
      "What would humility cost you?",
      "What do you refuse to examine because it feels justified?",
      "What part of you hides behind complexity?",
      "What do you keep unresolved to avoid change?",
      "What truth have you reduced to theory?",
      "What does your shadow gain from staying unseen?"
    ],
    "time": [
      "What are you postponing to a future that may not arrive?",
      "What version of you still lives in a past moment?",
      "What are you waiting to feel before beginning?",
      "What memory do you revisit when you feel uncertain?",
      "What part of your life feels unfinished?",
      "What are you rehearsing for a day that never comes?",
      "What regret quietly shapes your decisions?",
      "What do you assume you will “fix later”?",
      "What future are you living in instead of this moment?",
      "What would change if nothing was coming to save you?",
      "What chapter have you outgrown but not closed?",
      "What part of you fears time moving forward?",
      "What unfinished conversation still echoes?",
      "What future are you postponing your life for?",
      "What moment still defines you?",
      "What are you rushing toward?",
      "What are you reluctant to release?",
      "What part of you lives in anticipation rather than experience?",
      "What regret do you avoid naming?",
      "What do you assume will always be available?",
      "What are you afraid will happen if you slow down?",
      "What identity survives because you reference your past?",
      "What do you believe time will heal that you haven’t touched?",
      "Who are you without your timeline?",
      "What part of you depends on “not yet”?",
      "What would remain if your past stopped explaining you?",
      "What future do you fear more than you admit?",
      "What are you rehearsing that hasn’t happened?",
      "What part of you believes there will be more time?",
      "What would change if nothing was coming?",
      "What identity exists only because of memory?",
      "What do you keep reliving to stay consistent?",
      "What moment do you avoid revisiting?",
      "What part of you feels behind?",
      "What does your waiting prevent?",
      "What if this is not a transition but a life?",
      "What part of you measures worth by progress?",
      "What are you postponing joy for?",
      "What would it mean to arrive now?",
      "What part of you fears that it is already too late?",
      "What do you assume you will have time to repair?",
      "What are you avoiding by imagining a different future?",
      "If time dissolved, what would still matter?",
      "What story about your life feels overdue for revision?",
      "What part of you believes you are late?",
      "What would happen if you stopped forecasting your own future?",
      "What identity depends on being “in progress”?",
      "What chapter are you afraid to end?",
      "What moment keeps asking to be grieved?",
      "What do you hope time will erase?",
      "What are you afraid will happen if nothing changes?",
      "What does your sense of “too early” protect?",
      "What part of you fears arriving?",
      "What are you holding open that wants closure?",
      "What if this ordinary day is not temporary?",
      "What future have you been postponing living?",
      "What memory shapes your current fear?",
      "What identity dissolves when you stop measuring time?",
      "What are you delaying that already wants to begin?",
      "What if nothing is coming next?",
      "If this moment were complete, what would you stop chasing?",
      "What is present without reference to time?"
    ],
    "silence": [
      "Who are you in the silence after your name?",
      "What part of you feels constructed?",
      "What if the “real you” is less dramatic than you think?",
      "What identity would dissolve if no one compared you?",
      "Who are you when you are not anticipating reaction?",
      "What part of you was built to survive admiration?",
      "What version of you feels most exhausting to maintain?",
      "What if your strengths are disguises?",
      "Who are you when you are not improving?",
      "What part of you fears being ordinary?",
      "What if your identity is an agreement you forgot making?",
      "Who are you before preference forms?",
      "What would it mean to stop identifying with your wounds?",
      "What part of you feels most conditional?",
      "What if nothing about you is fixed?",
      "What would change if you stopped interpreting silence as rejection?",
      "Who are you when you are not being mirrored back?",
      "What part of you fears equality?",
      "What dynamic do you sustain because it feels familiar?",
      "What are you afraid would happen if you were fully honest?",
      "What role do you slip into without noticing?",
      "What part of you thrives on being needed?",
      "What are you mistaking for connection?",
      "Who are you when someone disagrees with you?",
      "What part of you resents what you once volunteered to give?",
      "What expectation feels invisible but heavy?",
      "What are you protecting when you avoid confrontation?",
      "What part of you wants closeness but fears exposure?",
      "What story do you repeat about how others treat you?",
      "What do you withdraw when you feel unseen?",
      "What part of you equates distance with safety?",
      "What would intimacy look like without performance?",
      "If no one completed you, who would you be?",
      "What remains when the question fades?",
      "Who are you before you answer?",
      "What is here without explanation?",
      "What changes when you stop seeking meaning?",
      "What is present before thought names it?",
      "Who are you without responding?",
      "What remains if nothing is solved?",
      "What is aware of this moment?",
      "What exists without effort?",
      "What if nothing needs to be understood?",
      "What remains when interpretation pauses?",
      "Who is noticing this question?",
      "What is here without narrative?",
      "What if there is nothing missing?",
      "What is unchanged by your story?",
      "What remains when you stop improving?",
      "Who are you without reference?",
      "What is aware of your searching?",
      "What if the answer is unnecessary?",
      "What is left when striving dissolves?",
      "Who is the one trying to awaken?",
      "What is aware of your effort to be aware?",
      "If you stop observing, what remains?",
      "What sees the thought “I”?",
      "What is here without identity?",
      "Who is seeking silence?",
      "What remains if the seeker disappears?",
      "What is before the next thought?",
      "Who is waiting for resolution?",
      "What is aware of confusion?",
      "If nothing is missing, what are you searching for?",
      "Who is aware of the one who is aware?",
      "If the observer disappears, what is left?",
      "What is present without perspective?",
      "Where is the boundary between inside and outside?",
      "Who owns this moment?",
      "What remains if there is no witness?",
      "What is here without separation?",
      "What is here when nothing is happening?",
      "If there is no one inside, what is outside?",
      "What remains when the need to understand collapses?",
      "Who would you be without the memory of being you?",
      "What is prior to awareness?",
      "If there is no observer, what is observed?",
      "What is here before the idea of here?",
      "Where does experience occur without a center?",
      "Who is asking this?",
      "What remains if the question has no answer?",
      "What is untouched by perception?",
      "Where does silence begin?",
      "What remains when identity is not asserted?",
      "Who would you be without memory?",
      "What exists without separation?",
      "If nothing is missing, what is this movement?",
      "What stands before thought?",
      "Who is prior to the sense of “I am”?",
      "What is here without effort to hold it?",
      "If the center cannot be located, what stabilizes?",
      "What is present even when ignored?",
      "Who dissolves when attention rests?",
      "What remains when nothing needs to remain?"
    ]
  },
  "es": {
    "self": [
      "¿Qué parte de ti sigues mostrando aunque ya no te representa?",
      "¿Quién serías si dejaras de explicarte tanto?",
      "¿Qué imagen tuya sientes que tienes que sostener?",
      "¿Cuándo empezaste a convertirte en esa versión de ti?",
      "¿Qué aspecto tuyo nació para encajar… y se quedó demasiado tiempo?",
      "Si nadie esperara nada de ti, ¿cómo te moverías?",
      "¿Qué parte de ti aparece sólo cuando estás a solas?",
      "¿Qué historia sobre ti repites aunque ya no te convence?",
      "¿Qué parte tuya te cuesta mirar de frente?",
      "¿En qué momento empezaste a ser “el fuerte”, “la responsable”, “el que puede”?",
      "¿Qué versión tuya se siente más liviana?",
      "¿Qué parte de ti está cansada de sostenerse?",
      "¿Quién eres cuando no estás cumpliendo ningún rol?",
      "¿Qué rasgo tuyo fue una defensa… y ahora es una costumbre?",
      "¿Qué parte de ti sólo quiere descansar de ser quien eres?",
      "¿Qué dejarías caer si no tuvieras que demostrar nada?",
      "¿Qué miedo sostiene la imagen que das?",
      "¿Qué parte de ti cambió… pero nadie lo notó?",
      "¿Qué estás sosteniendo de ti por lealtad al pasado?",
      "Si te quitaras las expectativas, ¿qué quedaría?",
      "¿Qué parte de ti aprendió a ser fuerte demasiado pronto?",
      "¿Qué imagen tuya te pesa, pero no sabes cómo soltar?",
      "¿Quién serías si no tuvieras que sostener a nadie?",
      "¿Qué parte de ti se formó para no molestar?",
      "¿Qué versión tuya se activa cuando temes perder cariño?",
      "¿Qué parte de ti sigue buscando aprobación en silencio?",
      "¿En qué momentos sientes que actúas más que ser?",
      "¿Qué parte de ti se endureció… y ya no sabe aflojar?",
      "¿Qué historia sobre ti empezó como protección?",
      "¿Qué parte tuya quiere cambiar, pero teme el juicio?",
      "¿Qué rasgo tuyo nació del miedo a quedar afuera?",
      "¿Qué parte de ti se siente invisible aunque esté presente?",
      "¿Qué estás defendiendo cuando dices “así soy yo”?",
      "¿Qué parte de ti se quedó en una etapa que ya pasó?",
      "¿Qué versión tuya se siente más auténtica, pero menos aceptada?",
      "¿Qué parte de ti se cansó de sostener la calma?",
      "¿Qué imagen tuya te impide mostrar fragilidad?",
      "¿Qué parte de ti aprendió a callar para pertenecer?",
      "¿Qué rasgo tuyo fue útil antes… y ahora te limita?",
      "Si dejaras de adaptarte, ¿qué aparecería?",
      "¿Qué parte de ti cambió para no perder afecto?",
      "¿Quién eres cuando nadie te está evaluando?",
      "¿Qué imagen tuya sientes que tienes que proteger?",
      "¿Qué parte de ti se acostumbró a rendir?",
      "¿Qué versión tuya aparece cuando tienes miedo de fallar?",
      "¿Qué parte de ti aprendió a no necesitar?",
      "¿Quién eres cuando no estás cumpliendo expectativas?",
      "¿Qué rasgo tuyo nació para agradar?",
      "¿Qué parte de ti se siente más verdadera, pero menos mostrada?",
      "¿Qué imagen tuya te enseñaron a sostener?",
      "¿Quién eres cuando dejas de justificarte?",
      "¿Qué parte de ti se volvió fuerte para no sentir vergüenza?",
      "¿Qué versión tuya se activa cuando quieres pertenecer?",
      "¿Qué parte de ti se acostumbró a ser “la que entiende”?",
      "¿Qué historia sobre ti heredaste sin cuestionar?",
      "¿Qué parte de ti aprendió a no pedir?",
      "¿Quién eres cuando no estás comparándote?",
      "¿Qué rasgo tuyo se volvió identidad por repetición?",
      "¿Qué parte de ti se siente más ligera cuando nadie mira?",
      "¿Qué imagen tuya temes perder?",
      "¿Qué parte de ti sigue intentando ser suficiente?",
      "¿Quién eres cuando no estás cumpliendo un rol?",
      "¿Qué parte de ti se acostumbró a anticipar el conflicto?",
      "¿Qué versión tuya aparece cuando temes decepcionar?",
      "¿Qué parte de ti aprendió a callar para no incomodar?",
      "¿Qué imagen tuya sostienes por lealtad?",
      "¿Quién eres cuando bajas la guardia?",
      "¿Qué parte de ti se siente más honesta en silencio?",
      "¿Qué rasgo tuyo nació del miedo al rechazo?",
      "¿Qué parte de ti se volvió adulta demasiado pronto?",
      "¿Qué versión tuya se activa cuando buscas aprobación?",
      "¿Qué parte de ti sigue esperando validación?",
      "¿Quién eres cuando nadie necesita nada de ti?",
      "¿Qué parte de ti se siente más frágil de lo que muestras?",
      "¿Qué imagen tuya aprendiste a defender?",
      "¿Qué parte de ti se construyó para no quedar afuera?",
      "¿Quién eres cuando no estás siendo útil?",
      "¿Qué parte de ti teme mostrarse tal como es?",
      "¿Qué versión tuya aparece cuando te sientes inseguro?",
      "¿Qué parte de ti cambió para sostener vínculos?",
      "¿Qué imagen tuya se siente más pesada hoy?",
      "¿Qué parte de ti se quedó esperando algo que no llegó?",
      "¿Qué parte de ti se pierde cuando intentas agradar?",
      "¿Quién eres cuando no estás reaccionando?",
      "¿Qué dinámica existe porque tú también la sostienes?",
      "¿Qué pasaría si dejaras de explicarte tanto?",
      "¿Qué parte de ti se siente más cómoda en desequilibrio?",
      "¿Qué estás enseñando a otros a esperar de ti?",
      "¿Quién eres cuando dejas de compensar?",
      "¿Qué parte de ti teme que la conozcan de verdad?",
      "¿Qué cambiaría si no intentaras mantener la armonía todo el tiempo?",
      "¿Qué rol tomas cuando aparece tensión?",
      "¿Qué parte de ti confunde atención con afecto?",
      "¿Qué dinámica se disolvería si soltaras el miedo?",
      "¿Qué parte de ti es leal a lo que ya no te hace bien?",
      "¿Quién eres cuando no estás buscando cerrar el conflicto?",
      "¿Qué expectativa nunca te has atrevido a nombrar?",
      "¿Qué parte de ti mantiene el vínculo predecible?",
      "¿Cómo sería vincularte sin estrategia?",
      "¿Qué parte de ti se siente amenazada por la independencia del otro?",
      "¿Qué cambia si sueltas la necesidad de que te entiendan?",
      "¿Quién eres cuando no te defines por cómo te tratan?",
      "¿Qué parte de ti busca control de forma silenciosa?",
      "¿Qué historia repites para justificar una dinámica?",
      "¿Qué pasaría si dejaras de ganarte el cariño?",
      "¿Qué parte de ti se siente más segura con distancia?",
      "Si no necesitaras que el otro te confirme, ¿qué quedaría?",
      "¿Qué estás evitando mirar en ti?",
      "¿Qué parte de ti prefieres no reconocer?",
      "¿Qué criticas en otros que te incomoda en ti mismo?",
      "¿Qué deseo tuyo has llamado poco realista para no asumirlo?",
      "¿Qué emoción transformas en explicación?",
      "¿Qué necesidad tuya te da vergüenza?",
      "¿Qué quieres, pero no te atreves a decir?",
      "¿Qué patrón repites aunque sabes que no te hace bien?",
      "¿Qué parte de ti envidia lo que dice no necesitar?",
      "¿Qué miedo disfrazas de firmeza?",
      "¿Qué estás postergando que sí importa?",
      "¿Qué costumbre te protege de sentirte vulnerable?",
      "¿Qué alivio sientes al no enfrentar algo?",
      "¿Qué inseguridad escondes detrás de seguridad?",
      "¿Qué responsabilizas en otros que también haces tú?",
      "¿Qué parte de ti se acomoda en la evasión?",
      "¿Qué minimizas para no tocar el dolor?",
      "¿Qué historia te cuentas para no hacerte cargo?",
      "¿Qué parte de ti se resiste a cambiar?",
      "Si dejaras de distraerte, ¿qué aparecería?",
      "¿Qué parte de ti obtiene algo al quedarse donde está?",
      "¿Qué haces como si no entendieras?",
      "¿Qué exigencia haces a otros que tú no cumples?",
      "¿Qué deseo ajeno te incomoda porque lo reconoces en ti?",
      "¿Qué parte de ti teme ser común?",
      "¿Qué explicas de más para no ser cuestionado?",
      "¿Qué hábito te evita el riesgo de que te rechacen?",
      "¿Qué envidia transformas en crítica?",
      "¿Qué verdad te resulta incómoda admitir?",
      "¿Qué parte de ti prefiere culpar antes que asumir?",
      "¿Qué estás protegiendo al postergar?",
      "¿Qué inseguridad se esconde detrás de tu impulso por lograr?",
      "¿Qué patrón continúa porque te resulta conocido?",
      "¿Qué imagen sostienes para ocultar duda?",
      "¿Qué parte de ti evita hacerse cargo?",
      "¿Qué llamas prudencia que podría ser miedo?",
      "¿Qué disculpa nunca has dado?",
      "¿Qué parte de ti quiere reconocimiento pero evita exponerse?",
      "¿Qué incomodidad pones en otros en lugar de sostenerla tú?",
      "Si dejaras de justificarte, ¿qué verías?",
      "¿Qué parte de ti busca comprensión más que cambio?",
      "¿Qué usas como “conciencia” para no moverte?",
      "¿Qué contradicción sostienes sin cuestionar?",
      "¿Qué rasgo defiendes como “así soy” aunque te limite?",
      "¿Qué evitas porque lograrlo te dejaría expuesto?",
      "¿Qué exageras para no mostrar inseguridad?",
      "¿Qué parte de ti influye sin decirlo abiertamente?",
      "¿Qué temes que se caiga si dices toda la verdad?",
      "¿Qué parte de ti prefiere controlar antes que confiar?",
      "¿Qué historia repites para sentirte con razón?",
      "¿Qué esperas que cambie sin hacer nada distinto?",
      "¿Qué parte de ti se siente cómoda siendo malinterpretada?",
      "¿Qué miedo sostiene tu opinión más firme?",
      "¿Qué patrón se rompería si dejaras de sentirte víctima?",
      "¿Qué parte de ti necesita destacar?",
      "¿Qué aspecto tuyo sientes secretamente superior?",
      "¿Qué parte de ti resiste reconocer error?",
      "¿Qué llamas “cuidarte” que podría ser evasión?",
      "¿Qué incomodidad disfrazas de ocupación?",
      "Si dejaras de repetir tu dolor, ¿qué quedaría?",
      "¿Qué parte de ti necesita mantenerse en conflicto?",
      "¿Qué perderías si reconocieras que te equivocaste?",
      "¿Qué imagen tuya se sostiene con pequeñas omisiones?",
      "¿Qué esperas que nunca salga a la luz?",
      "¿Qué proteges al mantener cierta dureza?",
      "¿Qué parte de ti necesita que otro falle?",
      "¿Qué incomodidad implicaría crecer de verdad?",
      "¿Qué criticas porque en algún momento lo deseaste?",
      "¿Qué te costaría bajar la defensa?",
      "¿Qué evitas revisar porque sientes que tienes razón?",
      "¿Qué parte de ti se esconde detrás de explicaciones largas?",
      "¿Qué mantienes sin resolver para no cambiar?",
      "¿Qué verdad transformaste en idea para no sentirla?",
      "¿Qué parte de ti sabotea cuando algo empieza a ir bien?",
      "¿Qué temes convertirte si te va bien?",
      "¿Qué inseguridad se disfraza de criterio?",
      "¿Qué defiendes aunque ya no te hace bien?",
      "¿Qué se derrumbaría si dejaras de culpar?",
      "¿Qué parte de ti teme hacerse cargo por completo?",
      "¿Qué gana tu sombra al pasar desapercibida?",
      "¿Qué autocrítica usas para no cambiar de verdad?",
      "¿Qué justificas que en el fondo te cuesta?",
      "¿Qué deseo apartaste para sostener tu imagen?",
      "¿Qué incomodidad colocas afuera en vez de mirarla?",
      "Si aceptaras todo lo que eres, ¿qué se integraría?",
      "¿Qué estás dejando para “más adelante”?",
      "¿Qué parte de ti sigue viviendo en otro momento?",
      "¿Qué estás esperando sentir antes de empezar?",
      "¿Qué recuerdo vuelves a mirar cuando dudas?",
      "¿Qué etapa tuya sientes inconclusa?",
      "¿Qué estás preparando para un día que no llega?",
      "¿Qué arrepentimiento influye en tus decisiones?",
      "¿Qué piensas resolver después y no ahora?",
      "¿Qué futuro te distrae del presente?",
      "¿Qué cambiaría si nada viniera a rescatarte?",
      "¿Qué capítulo ya terminó, pero no lo has aceptado?",
      "¿Qué promesa te hiciste y dejaste pasar?",
      "¿Qué momento quisieras volver a rehacer?",
      "¿Qué parte de ti se quedó en otra etapa?",
      "¿Qué sigues trayendo del pasado que ya no corresponde?",
      "¿Qué te da miedo si dejas de planificar?",
      "¿Qué meta crees que te dará tranquilidad definitiva?",
      "¿Qué evitas al quedarte en la nostalgia?",
      "¿Qué te protege la idea de “algún día”?",
      "Si este fuera el único momento disponible, ¿qué importaría?",
      "¿Qué te dices sobre el “después” para no cambiar ahora?",
      "¿Qué parte de ti teme que el tiempo avance?",
      "¿Qué conversación pendiente sigue resonando?",
      "¿Qué futuro usas como excusa para no vivir hoy?",
      "¿Qué momento sigue marcando tu identidad?",
      "¿Hacia dónde sientes que te apuras?",
      "¿Qué te cuesta soltar aunque ya pasó?",
      "¿Qué parte de ti vive en la expectativa?",
      "¿Qué arrepentimiento evitas nombrar?",
      "¿Qué das por hecho que siempre estará?",
      "¿Qué temes si bajas el ritmo?",
      "¿Qué versión tuya sigue explicándose desde el pasado?",
      "¿Qué esperas que el tiempo resuelva solo?",
      "¿En quién crees que te convertirás “cuando”?",
      "¿Qué protege tu sensación de urgencia?",
      "¿Qué sigues dejando abierto que ya terminó?",
      "¿Qué imagen futura sostiene tu presente?",
      "¿Qué parte de ti añora “antes”?",
      "¿Qué pasaría si nada cambiara?",
      "¿Con qué comparas tu propia vida?",
      "¿Qué verdad sigues evitando decirte?",
      "¿Qué parte de ti necesita dejar de aparentar?",
      "¿Qué emoción tuya pide ser reconocida sin explicación?",
      "¿Qué silencio te está hablando?",
      "¿Qué estás sintiendo que aún no aceptas?",
      "¿Qué parte de ti necesita un “ya basta”?",
      "¿Qué verdad te daría alivio si la admitieras?",
      "¿Qué callas para no alterar el equilibrio?",
      "¿Qué parte de ti quiere ser vista sin defenderse?",
      "¿Qué emoción tuya necesita espacio sin juicio?",
      "¿Qué estás listo para reconocer en privado?",
      "¿Qué parte de ti se siente más clara cuando te detienes?",
      "¿Qué silencio tuyo es en realidad miedo?",
      "¿Qué verdad pequeña cambiaría mucho si la asumieras?",
      "¿Qué parte de ti está esperando tu propia honestidad?",
      "¿Qué necesitas admitir sin justificarte?",
      "¿Qué emoción se vuelve más evidente cuando nadie opina?",
      "¿Qué parte de ti quiere dejar de sostener la imagen?",
      "¿Qué silencio tuyo contiene tristeza?",
      "¿Qué estás listo para aceptar, aunque no lo digas en voz alta?"
    ],
    "relationship": [
      "¿Qué parte de ti aparece sólo con cierta persona?",
      "¿Quién eres cuando quieres que te quieran?",
      "¿Qué aceptas para no quedarte solo?",
      "¿Qué versión tuya surge cuando sientes cercanía?",
      "¿Qué miedo sostiene tu forma de vincularte?",
      "¿Qué estás esperando que alguien note sin decirlo?",
      "¿Qué parte de ti se adapta demasiado rápido?",
      "¿Qué llamas cariño que en el fondo es necesidad?",
      "¿Qué silencio mantienes para evitar conflicto?",
      "¿Qué dinámica repites aunque sabes cómo termina?",
      "¿Qué parte de ti se activa cuando temes perder a alguien?",
      "¿Qué estás sosteniendo por lealtad más que por deseo?",
      "¿Qué parte de ti se siente pequeña frente a alguien?",
      "¿Qué estás esperando que el otro cambie para sentir alivio?",
      "¿Qué límite te cuesta poner?",
      "¿Qué parte de ti busca aprobación en cada vínculo?",
      "¿Qué emoción escondes detrás de la paciencia?",
      "¿Qué parte de ti necesita ser elegida?",
      "¿Qué estás dando que en realidad esperas recibir?",
      "Si dejaras de acomodarte, ¿qué pasaría?",
      "¿Qué parte de ti se siente responsable por el ánimo de otros?",
      "¿Qué estás evitando decir por miedo a incomodar?",
      "¿Qué dinámica repites aunque prometiste no volver ahí?",
      "¿Qué parte de ti teme quedar fuera?",
      "¿Qué estás sosteniendo por costumbre?",
      "¿Qué parte de ti busca seguridad en el control?",
      "¿Qué emoción tuya se activa cuando alguien se aleja?",
      "¿Qué estás esperando que el otro adivine?",
      "¿Qué parte de ti se endurece cuando te sientes herido?",
      "¿Qué estás confundiendo con compromiso?",
      "¿Qué parte de ti se siente desplazada fácilmente?",
      "¿Qué silencio tuyo se volvió distancia?",
      "¿Qué estás pidiendo sin asumirlo?",
      "¿Qué parte de ti teme no ser suficiente para alguien?",
      "¿Qué historia repites cuando sientes abandono?",
      "¿Qué parte de ti se adapta por miedo a perder el vínculo?",
      "¿Qué estás evitando enfrentar en ti, usando al otro?",
      "¿Qué parte de ti se activa cuando sientes comparación?",
      "¿Qué estás sosteniendo que ya no se siente recíproco?",
      "Si dejaras de anticipar rechazo, ¿cómo cambiaría tu forma de estar?"
    ],
    "body": [
      "¿En qué parte de tu cuerpo sientes tensión al hablar?",
      "¿Qué cambia en tu respiración cuando te sientes expuesto?",
      "¿Dónde sientes alivio cuando algo se resuelve?",
      "¿Qué parte de tu cuerpo se activa cuando tienes miedo?",
      "¿Qué emoción aparece primero en tu cuerpo?",
      "¿Dónde se instala el cansancio?",
      "¿Qué parte de tu cuerpo se endurece cuando te defiendes?",
      "¿Dónde sientes la verdad antes de decirla?",
      "¿Qué cambia en tu postura cuando te sientes seguro?",
      "¿Qué parte de tu cuerpo pide descanso y no la escuchas?",
      "¿Dónde se acumula lo que no expresas?",
      "¿Qué sientes en el pecho cuando algo te duele?",
      "¿Qué parte de tu cuerpo anticipa el conflicto?",
      "¿Dónde aparece la ansiedad?",
      "¿Qué cambia en tu cuerpo cuando confías?",
      "¿Qué parte de ti se relaja cuando te sientes comprendido?",
      "¿Dónde sientes la vergüenza?",
      "¿Qué parte de tu cuerpo te habla con más claridad?",
      "¿Dónde se queda el enojo cuando no lo expresas?",
      "Si escucharas tu cuerpo sin juicio, ¿qué notarías?",
      "¿Qué sensación aparece antes de que pongas palabras?",
      "¿Dónde sientes un leve movimiento cuando estás en calma?",
      "¿Qué parte de tu cuerpo se enciende cuando estás inspirado?",
      "¿Dónde se te cae la energía cuando dices que sí sin querer?",
      "¿Qué cambia en tu espalda cuando te sientes seguro?",
      "¿Dónde se expande tu respiración cuando confías?",
      "¿Qué corriente sutil recorre tu cuerpo cuando eres honesto?",
      "¿Dónde sientes que algo se apaga cuando te sobrecargas?",
      "¿Qué sensación queda después de una conversación intensa?",
      "¿Dónde se siente más liviano tu cuerpo?",
      "¿Qué pasa en tu estómago cuando dudas?",
      "¿Dónde se instala la expectativa en tu cuerpo?",
      "¿Qué parte de ti se activa justo antes de actuar?",
      "¿Dónde notas una pausa en tu respiración?",
      "¿Qué calor sutil aparece cuando sueltas rencor?",
      "¿Dónde se contrae tu cuerpo cuando te sientes juzgado?",
      "¿Qué sensación surge antes de que aparezca la emoción?",
      "¿Dónde te sientes más presente físicamente?",
      "¿Qué cambia en tu pulso cuando dices algo importante?",
      "Si siguieras esa energía interna, ¿hacia dónde te llevaría?",
      "¿Qué sabe tu cuerpo que sigues postergando?",
      "¿Dónde se siente tu cuerpo más en casa?",
      "¿Qué cambia cuando dejas de exigirte?",
      "¿Hacia dónde se inclina tu cuerpo cuando algo te atrae?",
      "¿Qué se relaja en ti cuando te sientes respetado?",
      "¿Dónde guarda tu cuerpo conversaciones pendientes?",
      "¿Qué parte de tu cuerpo se siente pesada sin razón clara?",
      "¿Dónde se siente más abierto tu cuerpo?",
      "¿Qué cambia en tus hombros cuando sueltas el control?",
      "¿Qué recuerda tu cuerpo que tu mente dejó atrás?",
      "¿Qué sensación te avisa que estás cruzando tu propio límite?",
      "¿Dónde te sientes más vivo físicamente?",
      "¿Qué leve temblor aparece antes de atreverte?",
      "¿Dónde se ablanda tu cuerpo cuando te sientes seguro?",
      "¿Qué sensación crece cuando estás por decir algo importante?",
      "¿Dónde se tensa tu cuerpo con ciertas personas?",
      "¿Qué parte de tu cuerpo se siente desbordada?",
      "¿Dónde te preparas para una decepción?",
      "¿Qué sensación queda cuando no expresas lo que sientes?",
      "Si tu cuerpo guiara tus decisiones, ¿qué cambiaría?",
      "¿Qué sensación existe antes de que la interpretes?",
      "¿Dónde se siente tu cuerpo más transparente?",
      "¿Qué cambia cuando apoyas bien los pies en el suelo?",
      "¿Dónde pulsa tu cuerpo cuando estás en silencio?",
      "¿Qué parte de ti se siente sutilmente activada ahora?",
      "¿Dónde sientes algo pendiente en tu cuerpo?",
      "¿Qué sensación aparece cuando dejas la historia de lado?",
      "¿Dónde se siente tu cuerpo sin defensa?",
      "¿Qué ocurre físicamente cuando estás completamente presente?",
      "¿Dónde se reúne tu energía antes de moverte?",
      "¿Qué parte de tu cuerpo se siente como una puerta?",
      "¿Dónde se siente tu cuerpo menos separado del entorno?",
      "¿Qué sensación crece cuando permites la quietud?",
      "¿Dónde resiste tu cuerpo soltar?",
      "¿Qué vibración sutil aparece cuando dejas de luchar con lo que sientes?",
      "¿Dónde se siente tu cuerpo más honesto?",
      "¿Qué pasa en tu cuerpo cuando te permites ser común?",
      "¿Dónde sientes tu respiración con más claridad?",
      "¿Qué sensación permanece cuando la mente se aquieta?",
      "¿Dónde se siente tu cuerpo más firme en el suelo?",
      "¿Qué parte de ti se abre sin esfuerzo?",
      "¿Dónde sientes que tu cuerpo escucha?",
      "¿Qué cambia cuando aflojas la mandíbula?",
      "¿Dónde se siente tu cuerpo como presencia pura?",
      "Si permanecieras plenamente en tu cuerpo por un minuto, ¿qué podría disolverse?",
      "¿Qué cambia cuando dejas de resistirte?",
      "¿Qué parte de ti se relaja al admitir lo evidente?",
      "¿Qué verdad se siente más liviana cuando la aceptas?",
      "¿Qué emoción tuya ya no necesita explicación?",
      "¿Qué parte de ti se aquieta cuando dejas de pelear?",
      "¿Qué silencio trae claridad en lugar de tensión?",
      "¿Qué estás listo para soltar sin anuncio?",
      "¿Qué parte de ti se siente más sincera cuando callas?",
      "¿Qué cambia cuando no intentas convencer a nadie?",
      "¿Qué emoción pierde fuerza cuando la miras directo?",
      "¿Qué parte de ti se siente más estable al aceptar?",
      "¿Qué silencio tuyo ya no duele como antes?",
      "¿Qué verdad no necesita defensa?",
      "¿Qué parte de ti puede quedarse quieta sin miedo?",
      "¿Qué cambia cuando no intentas arreglar nada?",
      "¿Qué emoción se suaviza cuando la reconoces?",
      "¿Qué parte de ti se siente más completa cuando te detienes?",
      "¿Qué silencio deja de ser carga y se vuelve descanso?",
      "¿Qué estás listo para permitir que sea?",
      "¿Qué parte de ti ya no necesita explicación?"
    ],
    "shadow": [],
    "time": [
      "¿Quién eres sin tu propia cronología?",
      "¿Qué parte de ti vive en el “todavía no”?",
      "¿Qué quedaría si el pasado dejara de explicarte?",
      "¿Qué futuro temes más de lo que reconoces?",
      "¿Qué estás ensayando que aún no ocurre?",
      "¿Qué parte de ti cree que siempre habrá más tiempo?",
      "¿Qué cambiaría si nada nuevo llegara?",
      "¿Qué identidad tuya se sostiene en un recuerdo?",
      "¿Qué momento repites para mantener coherencia?",
      "¿Qué experiencia evitas volver a mirar?",
      "¿Qué parte de ti siente que va atrasada?",
      "¿Qué te impide la espera?",
      "¿Y si esto no fuera una etapa, sino tu vida?",
      "¿Qué parte de ti mide su valor por avance?",
      "¿Qué estás dejando para después que podrías vivir hoy?",
      "¿Qué significaría llegar ahora?",
      "¿Qué parte de ti teme que ya sea tarde?",
      "¿Qué asumes que podrás reparar con más tiempo?",
      "¿Qué evitas al imaginar otro futuro?",
      "Si el tiempo no fuera lineal, ¿qué importaría?",
      "¿Qué historia sobre tu vida necesita ser revisada?",
      "¿Qué parte de ti siente que llegó tarde?",
      "¿Qué pasaría si dejaras de anticipar tu propio futuro?",
      "¿Qué identidad tuya depende de estar “en proceso”?",
      "¿Qué etapa temes cerrar?",
      "¿Qué momento necesita ser reconocido con tristeza?",
      "¿Qué esperas que el tiempo borre?",
      "¿Qué temes si nada cambia?",
      "¿Qué protege tu sensación de que “no es el momento”?",
      "¿Qué parte de ti teme llegar?",
      "¿Qué sigues manteniendo abierto que ya terminó?",
      "¿Y si este día común no fuera una pausa?",
      "¿Qué futuro estás postergando vivir?",
      "¿Qué recuerdo influye en tu miedo actual?",
      "¿Qué te dices sobre “cuando todo esté más tranquilo”?",
      "¿Qué significaría dejar de explicarte como alguien en evolución?",
      "¿Qué parte de ti vive sólo en la expectativa?",
      "¿Qué cambiaría si esto no fuera preparación?",
      "¿Qué arrepentimiento necesita reconocimiento más que solución?",
      "¿Qué parte de ti teme la quietud porque se siente definitiva?",
      "¿Qué ocurre si no hay después?",
      "¿Qué identidad se diluye cuando dejas de medir el tiempo?",
      "¿Qué estás postergando que ya quiere comenzar?",
      "¿Y si no viene nada más?",
      "Si este momento fuera suficiente, ¿qué dejarías de perseguir?"
    ],
    "silence": [
      "¿Qué parte de ti necesita sentirse indispensable?",
      "¿Qué emoción tuya proyectas sin darte cuenta?",
      "¿Qué cambiaría si dejaras de interpretar distancia como rechazo?",
      "¿Quién eres cuando no te están validando?",
      "¿Qué parte de ti teme ser vista tal como es?",
      "¿Qué dinámica te resulta conocida aunque te desgaste?",
      "¿Qué estás evitando decir por miedo a perder cercanía?",
      "¿Qué parte de ti se siente amenazada por la autonomía del otro?",
      "¿Qué estás sosteniendo por miedo a quedar solo?",
      "¿Qué parte de ti busca aprobación disfrazada de cariño?",
      "¿Quién eres cuando alguien no está de acuerdo contigo?",
      "¿Qué estás dando esperando que te devuelvan lo mismo?",
      "¿Qué parte de ti se siente desplazada con facilidad?",
      "¿Qué historia repites cuando alguien se aleja?",
      "¿Qué parte de ti confunde intensidad con conexión?",
      "¿Qué silencio tuyo se volvió resentimiento?",
      "¿Qué estás evitando mirar en ti al enfocarte en el otro?",
      "¿Qué parte de ti necesita controlar para sentirse seguro?",
      "¿Qué pasaría si dejaras de anticipar abandono?",
      "Si no necesitaras que te eligieran, ¿cómo te vincularías?",
      "¿Qué verdad guardas y no dices?",
      "¿Qué sientes que no has nombrado?",
      "¿Qué callas para mantener la calma?",
      "¿Qué parte de ti necesita ser escuchada en silencio?",
      "¿Qué emoción tuya sigue esperando espacio?",
      "¿Qué no estás diciendo por miedo a incomodar?",
      "¿Qué pesa más cuando te quedas quieto?",
      "¿Qué parte de ti sólo aparece cuando nadie habla?",
      "¿Qué necesitas admitir en voz baja?",
      "¿Qué sientes cuando todo se aquieta?",
      "¿Qué parte de ti quiere dejar de fingir?",
      "¿Qué verdad pequeña has estado evitando?",
      "¿Qué te dices sólo cuando estás solo?",
      "¿Qué parte de ti pide honestidad?",
      "¿Qué silencio tuyo no es paz?",
      "¿Qué emoción se vuelve más clara cuando paras?",
      "¿Qué necesitas reconocer sin explicarlo?",
      "¿Qué parte de ti quiere descansar de sostener?",
      "¿Qué se vuelve evidente cuando dejas de hablar?",
      "¿Qué estás listo para admitir, aunque sea en silencio?",
      "¿Qué queda cuando dejas de intentar entender?",
      "¿Qué cambia cuando aceptas sin discutir contigo?",
      "¿Qué parte de ti puede estar sin esfuerzo?",
      "¿Qué se siente cuando no intentas sostener nada?",
      "¿Qué verdad ya no necesita ser explicada?",
      "¿Qué parte de ti descansa cuando no hay presión?",
      "¿Qué cambia cuando no te justificas?",
      "¿Qué emoción pierde intensidad cuando la aceptas tal cual es?",
      "¿Qué parte de ti puede estar en silencio sin incomodidad?",
      "¿Qué se suaviza cuando sueltas la defensa?",
      "¿Qué ocurre cuando no buscas aprobación?",
      "¿Qué parte de ti se siente suficiente ahora?",
      "¿Qué cambia cuando no necesitas tener razón?",
      "¿Qué emoción deja de pesar cuando la reconoces?",
      "¿Qué parte de ti se aquieta sin esfuerzo?",
      "¿Qué se siente cuando no intentas corregirte?",
      "¿Qué verdad puede estar sin adornos?",
      "¿Qué parte de ti no necesita probar nada?",
      "¿Qué ocurre cuando no intentas mejorar el momento?",
      "¿Qué se siente cuando aceptas lo que ya es?",
      "¿Qué parte de ti puede quedarse en calma?",
      "¿Qué cambia cuando no huyes de lo que sientes?",
      "¿Qué silencio se vuelve alivio?",
      "¿Qué parte de ti puede simplemente estar?",
      "¿Qué ocurre cuando no falta nada?"
    ]
  }
};
